"""initial schema

Revision ID: 7bc82eba74f4
Revises: 
Create Date: 2026-07-07 18:42:14.940476
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7bc82eba74f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('scheduled_meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('invite_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'STARTED', 'CANCELLED', name='schedulestatus'), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_meetings_host_id'), 'scheduled_meetings', ['host_id'], unique=False)
    op.create_index(op.f('ix_scheduled_meetings_meeting_code'), 'scheduled_meetings', ['meeting_code'], unique=True)
    op.create_index(op.f('ix_scheduled_meetings_scheduled_start'), 'scheduled_meetings', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_scheduled_meetings_status'), 'scheduled_meetings', ['status'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('invite_url', sa.String(length=500), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='meetingstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('scheduled_meeting_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_meeting_id'], ['scheduled_meetings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_host_id'), 'meetings', ['host_id'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_code'), 'meetings', ['meeting_code'], unique=True)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_table('meeting_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.Enum('CREATED', 'JOINED', 'LEFT', 'ENDED', 'SCHEDULED', 'CANCELLED', name='meetingeventtype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_history_meeting_id'), 'meeting_history', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_history_user_id'), 'meeting_history', ['user_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', 'joined_at', name='uq_participant_session')
    )
    op.create_index(op.f('ix_participants_meeting_id'), 'participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_participants_user_id'), 'participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_meeting_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_meeting_history_user_id'), table_name='meeting_history')
    op.drop_index(op.f('ix_meeting_history_meeting_id'), table_name='meeting_history')
    op.drop_table('meeting_history')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_code'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_host_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_scheduled_meetings_status'), table_name='scheduled_meetings')
    op.drop_index(op.f('ix_scheduled_meetings_scheduled_start'), table_name='scheduled_meetings')
    op.drop_index(op.f('ix_scheduled_meetings_meeting_code'), table_name='scheduled_meetings')
    op.drop_index(op.f('ix_scheduled_meetings_host_id'), table_name='scheduled_meetings')
    op.drop_table('scheduled_meetings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
